#!/usr/bin/env bash
if [ $# -ne 1 ]
then
  echo 'Usage: factors <file>'
  exit 1
else

        while read i
        do
	        r=$(python3 factorization.py "$i")
        	num1=$r
	        num2=$(bc <<< "$i"/"$r")
	        result=$(echo "if($num2 > $num1) 1 else 0" | bc)
	        if ((result == 1)); then
		        num3=$num1
		        num1=$num2
		        num2=$num3
                fi
	        echo "$i=$num1*$num2"
        done < "$1"
fi
