#!/usr/bin/env bash

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                num2=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                num2=$(echo $a*$num2 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                num2=$3
        fi

        num1=$2
        num=$(echo "$1" | tr ':' '=')

        result=$(echo "if($num2 > $num1) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$num1
		        num1=$num2
		        num2=$numcp
                fi

        echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi

""" Class factor_file """
from sys import argv
from math import sqrt


class factor_file:
    """ init """
    def __init__(self, filename):
        """check if
        file is not NULL
        """
        if filename is not None:
            self.filename = filename

    def open_read_file(self):
        """read from file
        add to array
        """
        with open(self.filename, encoding="utf-8") as file:
            lines = file.readlines()
        number_to_factor = []
        for line in lines:
            number_to_factor.append(int(line))
        return number_to_factor

    def factorial(self, n):
        """factor each
        n given
        """
        for i in range(2, n):
            if n == ((n // i) * i):
                print("{}={}*{}".format(n, (n // i), i))
                break

    def factor_each_n_in_lis(self):
        """factor each
        num in ls
        """
        ls = self.open_read_file()
        for n in ls:
            self.factorial(n)


for i in range(1, len(argv)):
    factor_file(argv[i]).factor_each_n_in_lis()
